name: hexagrad
description: A Flutter app for SIH solution 25094 (AI-powered career guidance)

publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.0.5
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_gemini: ^3.0.0
  google_maps_flutter: ^2.5.0
  speech_to_text: ^6.3.0   # ✅ Added for voice input
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/