// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjkvrIMaRQ3_6HiXPa8VWtQRHq7ihajzE',
    appId: '1:570111097441:web:f73f841f27f53d571b0820',
    messagingSenderId: '570111097441',
    projectId: 'hexagrad',
    authDomain: 'hexagrad.firebaseapp.com',
    storageBucket: 'hexagrad.firebasestorage.app',
    measurementId: 'G-05MY5XB3TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeoLboJ4HdwVDQCXgDbJZ7YFagAIWOAO8',
    appId: '1:570111097441:android:05dd17f4ace1576e1b0820',
    messagingSenderId: '570111097441',
    projectId: 'hexagrad',
    storageBucket: 'hexagrad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDMX5lv-Dw4c5AmA_tr-KCMe12YSHyoc',
    appId: '1:570111097441:ios:1f83fabfdd7308171b0820',
    messagingSenderId: '570111097441',
    projectId: 'hexagrad',
    storageBucket: 'hexagrad.firebasestorage.app',
    androidClientId: '570111097441-aflbllgcquhqvc248fmgb0ca51t99oko.apps.googleusercontent.com',
    iosClientId: '570111097441-iogf0e8vhi19jbtun7rro2d308dsnt72.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexagrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXDMX5lv-Dw4c5AmA_tr-KCMe12YSHyoc',
    appId: '1:570111097441:ios:1f83fabfdd7308171b0820',
    messagingSenderId: '570111097441',
    projectId: 'hexagrad',
    storageBucket: 'hexagrad.firebasestorage.app',
    androidClientId: '570111097441-aflbllgcquhqvc248fmgb0ca51t99oko.apps.googleusercontent.com',
    iosClientId: '570111097441-iogf0e8vhi19jbtun7rro2d308dsnt72.apps.googleusercontent.com',
    iosBundleId: 'com.example.hexagrad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjkvrIMaRQ3_6HiXPa8VWtQRHq7ihajzE',
    appId: '1:570111097441:web:0c835314126067ce1b0820',
    messagingSenderId: '570111097441',
    projectId: 'hexagrad',
    authDomain: 'hexagrad.firebaseapp.com',
    storageBucket: 'hexagrad.firebasestorage.app',
    measurementId: 'G-T27C80Q960',
  );

}